import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] !== "dev";
const outDir = path.resolve(".obsidian/plugins/workos-dashboard");

// Ensure output directory exists
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

// Copy manifest.json
fs.copyFileSync(".src/manifest.json", path.join(outDir, "manifest.json"));

// Build CSS using tailwindcss CLI
function buildCSS() {
  try {
    execSync(`npx tailwindcss -i ./.src/styles/tailwind.css -o "${path.join(outDir, "styles.css")}" ${prod ? "--minify" : ""}`, {
      stdio: "inherit",
    });
    console.log("CSS build complete.");
  } catch (err) {
    console.error("CSS build failed:", err);
  }
}

buildCSS();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [".src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  console.log("Production build finished successfully!");
} else {
  await context.watch();
  console.log("Watching for changes...");
}
