/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Agent Lock Guard - Multi-Agent Concurrency & Collision Guard for Obsidian
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AgentLockGuardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/bannerView.ts
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  forceReadingModeOnLock: true,
  enableHardBlock: true,
  autoUnlockTimeoutMinutes: 0,
  showBanner: true,
  showTimer: true,
  stickyBanner: true,
  bannerStyle: "glassmorphism",
  enableStatusBar: true,
  hideStatusBarWhenZero: false,
  enableRibbonIcon: true,
  enableCompletionToasts: true,
  enableBlockedEditToasts: true
};

// src/bannerView.ts
var BannerViewManager = class {
  lockManager;
  settings = DEFAULT_SETTINGS;
  timerInterval = null;
  currentBannerEl = null;
  currentLockedFile = null;
  constructor(lockManager, settings) {
    this.lockManager = lockManager;
    if (settings)
      this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  init() {
    this.startTimerLoop();
  }
  destroy() {
    this.stopTimerLoop();
    this.removeBanner();
  }
  updateBannerForView(view) {
    if (!view || !view.file || !this.settings.showBanner) {
      this.removeBanner();
      return;
    }
    const file = view.file;
    const lockInfo = this.lockManager.getLockInfo(file);
    if (lockInfo && lockInfo.agentState === "processing") {
      this.renderBanner(view, lockInfo);
    } else {
      this.removeBanner();
    }
  }
  renderBanner(view, lockInfo) {
    this.currentLockedFile = lockInfo.file;
    const container = view.contentEl;
    let wrapperEl = container.querySelector(".agent-lock-banner-wrapper");
    if (!wrapperEl) {
      wrapperEl = createDiv({ cls: "agent-lock-banner-wrapper" });
      container.prepend(wrapperEl);
    }
    if (!this.settings.stickyBanner) {
      wrapperEl.addClass("not-sticky");
    } else {
      wrapperEl.removeClass("not-sticky");
    }
    let bannerEl = wrapperEl.querySelector(".agent-lock-banner");
    if (!bannerEl) {
      bannerEl = wrapperEl.createDiv({ cls: "agent-lock-banner" });
      this.currentBannerEl = bannerEl;
    }
    bannerEl.removeClass("style-glassmorphism", "style-solid", "style-minimal");
    bannerEl.addClass(`style-${this.settings.bannerStyle || "glassmorphism"}`);
    bannerEl.empty();
    const leftEl = bannerEl.createDiv({ cls: "agent-lock-banner-left" });
    const pulseWrapper = leftEl.createDiv({ cls: "agent-lock-pulse-wrapper" });
    pulseWrapper.createDiv({ cls: "agent-lock-pulse-core" });
    pulseWrapper.createDiv({ cls: "agent-lock-pulse-ring" });
    const iconEl = leftEl.createSpan({ cls: "agent-lock-icon" });
    (0, import_obsidian.setIcon)(iconEl, "bot");
    const badgeEl = leftEl.createSpan({ cls: "agent-lock-badge", text: "AGENT AKTIV" });
    const nameEl = leftEl.createSpan({ cls: "agent-lock-agent-name", text: lockInfo.lockedBy });
    const dividerEl = leftEl.createSpan({ cls: "agent-lock-divider", text: "\u2022" });
    const descEl = leftEl.createSpan({ cls: "agent-lock-status-desc", text: "Schreibgesch\xFCtzt" });
    const rightEl = bannerEl.createDiv({ cls: "agent-lock-banner-right" });
    if (this.settings.showTimer) {
      const timerBadge = rightEl.createDiv({ cls: "agent-lock-timer-badge" });
      const timerIcon = timerBadge.createSpan({ cls: "agent-lock-timer-icon" });
      (0, import_obsidian.setIcon)(timerIcon, "clock");
      const timerText = timerBadge.createSpan({ cls: "agent-lock-timer-text" });
      timerText.setText(this.calculateDurationText(lockInfo.lockedAtDate));
    }
    const unlockBtn = rightEl.createEl("button", {
      cls: "agent-lock-unlock-btn"
    });
    const unlockIcon = unlockBtn.createSpan({ cls: "agent-lock-unlock-btn-icon" });
    (0, import_obsidian.setIcon)(unlockIcon, "unlock");
    unlockBtn.createSpan({ text: "Freigeben" });
    unlockBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      unlockBtn.disabled = true;
      unlockBtn.setText("Wird freigegeben...");
      await this.lockManager.unlockFile(lockInfo.file);
    });
  }
  removeBanner() {
    if (this.currentBannerEl) {
      const wrapper = this.currentBannerEl.closest(".agent-lock-banner-wrapper");
      if (wrapper) {
        wrapper.remove();
      } else {
        this.currentBannerEl.remove();
      }
      this.currentBannerEl = null;
    }
    this.currentLockedFile = null;
  }
  startTimerLoop() {
    this.stopTimerLoop();
    this.timerInterval = window.setInterval(() => {
      if (!this.currentBannerEl || !this.currentLockedFile || !this.settings.showTimer)
        return;
      const lock = this.lockManager.getLockInfo(this.currentLockedFile);
      if (!lock)
        return;
      const timerTextEl = this.currentBannerEl.querySelector(".agent-lock-timer-text");
      if (timerTextEl) {
        timerTextEl.setText(this.calculateDurationText(lock.lockedAtDate));
      }
    }, 1e3);
  }
  stopTimerLoop() {
    if (this.timerInterval !== null) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  calculateDurationText(lockedAtDate) {
    if (!lockedAtDate)
      return "aktiv";
    const now = /* @__PURE__ */ new Date();
    const diffSec = Math.max(0, Math.floor((now.getTime() - lockedAtDate.getTime()) / 1e3));
    if (diffSec < 60) {
      return `vor ${diffSec}s`;
    }
    const mins = Math.floor(diffSec / 60);
    const remainingSec = diffSec % 60;
    return `vor ${mins}m ${remainingSec}s`;
  }
};

// src/editorExtension.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_obsidian2 = require("obsidian");
var appInstance = null;
var activeLockManager = null;
var activeSettings = DEFAULT_SETTINGS;
var lastNoticeTime = 0;
function setEditorLockManager(app, manager, settings) {
  appInstance = app;
  activeLockManager = manager;
  if (settings)
    activeSettings = settings;
}
function updateEditorLockSettings(settings) {
  activeSettings = settings;
}
function showLockNotice() {
  if (!activeSettings.enableBlockedEditToasts)
    return;
  const now = Date.now();
  if (now - lastNoticeTime > 2e3) {
    lastNoticeTime = now;
    new import_obsidian2.Notice("\u{1F512} Notiz ist durch KI-Agent gesperrt (Schreibschutz aktiv). Klicke oben auf 'Freigeben' zum Bearbeiten.", 3e3);
  }
}
function isCurrentViewLocked(viewDom) {
  if (!activeLockManager || activeLockManager.getAllActiveLocks().length === 0)
    return false;
  const leafDom = viewDom ? viewDom.closest(".workspace-leaf") : document.querySelector(".workspace-leaf.mod-active");
  if (leafDom?.querySelector(".agent-lock-banner") !== null) {
    return true;
  }
  if (appInstance) {
    const activeFile = appInstance.workspace.getActiveFile();
    if (activeFile && activeLockManager.isFileLocked(activeFile)) {
      return true;
    }
  }
  return false;
}
function createEditorLockExtension() {
  const transactionBlocker = import_state.EditorState.transactionFilter.of((tr) => {
    if (!activeLockManager || !tr.docChanged || !activeSettings.enableHardBlock)
      return tr;
    if (isCurrentViewLocked()) {
      showLockNotice();
      return [];
    }
    return tr;
  });
  const domHandlers = import_view.EditorView.domEventHandlers({
    keydown(event, view) {
      if (!activeLockManager)
        return false;
      if (event.key === "ArrowUp" || event.key === "ArrowDown" || event.key === "ArrowLeft" || event.key === "ArrowRight" || event.key === "PageUp" || event.key === "PageDown" || event.key === "Home" || event.key === "End" || event.key === "Escape" || event.key === "Control" || event.key === "Alt" || event.key === "Shift" || event.key === "Meta") {
        return false;
      }
      if (isCurrentViewLocked(view.dom)) {
        event.preventDefault();
        event.stopPropagation();
        showLockNotice();
        return true;
      }
      return false;
    },
    paste(event, view) {
      if (isCurrentViewLocked(view.dom)) {
        event.preventDefault();
        event.stopPropagation();
        showLockNotice();
        return true;
      }
      return false;
    },
    cut(event, view) {
      if (isCurrentViewLocked(view.dom)) {
        event.preventDefault();
        event.stopPropagation();
        showLockNotice();
        return true;
      }
      return false;
    },
    drop(event, view) {
      if (isCurrentViewLocked(view.dom)) {
        event.preventDefault();
        event.stopPropagation();
        showLockNotice();
        return true;
      }
      return false;
    }
  });
  return [transactionBlocker, domHandlers];
}

// src/lockManager.ts
var import_obsidian3 = require("obsidian");
var LockManager = class {
  app;
  locks = /* @__PURE__ */ new Map();
  listeners = /* @__PURE__ */ new Set();
  eventRefs = [];
  onFileCompletedCallback;
  autoUnlockTimer = null;
  settings = DEFAULT_SETTINGS;
  constructor(app, onFileCompleted) {
    this.app = app;
    this.onFileCompletedCallback = onFileCompleted;
  }
  updateSettings(settings) {
    this.settings = settings;
    this.restartAutoUnlockLoop();
  }
  init(settings) {
    if (settings)
      this.settings = settings;
    this.scanVault();
    const cacheRef = this.app.metadataCache.on("changed", (file) => {
      if (file instanceof import_obsidian3.TFile && file.extension === "md") {
        this.evaluateFile(file);
      }
    });
    this.eventRefs.push(cacheRef);
    const renameRef = this.app.vault.on("rename", (file, oldPath) => {
      if (this.locks.has(oldPath)) {
        const oldLock = this.locks.get(oldPath);
        this.locks.delete(oldPath);
        if (file instanceof import_obsidian3.TFile) {
          oldLock.file = file;
          oldLock.path = file.path;
          this.locks.set(file.path, oldLock);
          this.notifyListeners();
        }
      }
    });
    this.eventRefs.push(renameRef);
    const deleteRef = this.app.vault.on("delete", (file) => {
      if (this.locks.has(file.path)) {
        this.locks.delete(file.path);
        this.notifyListeners();
      }
    });
    this.eventRefs.push(deleteRef);
    this.restartAutoUnlockLoop();
  }
  destroy() {
    this.stopAutoUnlockLoop();
    for (const ref of this.eventRefs) {
      this.app.metadataCache.offref(ref);
      this.app.vault.offref(ref);
    }
    this.eventRefs = [];
    this.locks.clear();
    this.listeners.clear();
  }
  restartAutoUnlockLoop() {
    this.stopAutoUnlockLoop();
    if (this.settings.autoUnlockTimeoutMinutes > 0) {
      this.autoUnlockTimer = window.setInterval(() => {
        this.checkStaleLocks();
      }, 1e4);
    }
  }
  stopAutoUnlockLoop() {
    if (this.autoUnlockTimer !== null) {
      window.clearInterval(this.autoUnlockTimer);
      this.autoUnlockTimer = null;
    }
  }
  async checkStaleLocks() {
    if (this.settings.autoUnlockTimeoutMinutes <= 0)
      return;
    const maxSec = this.settings.autoUnlockTimeoutMinutes * 60;
    const now = Date.now();
    for (const lock of this.getAllActiveLocks()) {
      if (lock.lockedAtDate) {
        const diffSec = Math.floor((now - lock.lockedAtDate.getTime()) / 1e3);
        if (diffSec >= maxSec) {
          await this.unlockFile(lock.file);
          new import_obsidian3.Notice(
            `\u23F1\uFE0F Sperre f\xFCr "${lock.title}" nach ${this.settings.autoUnlockTimeoutMinutes} Min. automatisch freigegeben.`,
            5e3
          );
        }
      }
    }
  }
  scanVault() {
    const files = this.app.vault.getMarkdownFiles();
    this.locks.clear();
    for (const file of files) {
      const lockInfo = this.extractLockInfo(file);
      if (lockInfo && lockInfo.agentState === "processing") {
        this.locks.set(file.path, lockInfo);
      }
    }
    this.notifyListeners();
  }
  evaluateFile(file) {
    const previousLock = this.locks.get(file.path);
    const currentLock = this.extractLockInfo(file);
    if (currentLock && currentLock.agentState === "processing") {
      this.locks.set(file.path, currentLock);
      this.notifyListeners();
    } else {
      if (previousLock) {
        this.locks.delete(file.path);
        this.notifyListeners();
        if (this.onFileCompletedCallback) {
          this.onFileCompletedCallback(file, previousLock.lockedBy);
        }
      }
    }
  }
  extractLockInfo(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache || !cache.frontmatter)
      return null;
    const fm = cache.frontmatter;
    const agentState = fm.agent_state;
    const lockedBy = fm.locked_by || "KI-Agent";
    const lockedAt = fm.locked_at || null;
    if (agentState === "processing") {
      let lockedAtDate = null;
      if (lockedAt) {
        const parsed = new Date(lockedAt);
        if (!isNaN(parsed.getTime())) {
          lockedAtDate = parsed;
        }
      }
      return {
        file,
        path: file.path,
        title: fm.title || file.basename,
        agentState: "processing",
        lockedBy,
        lockedAt,
        lockedAtDate
      };
    }
    return null;
  }
  getLockInfo(file) {
    if (!file)
      return null;
    return this.locks.get(file.path) || null;
  }
  isFileLocked(file) {
    if (!file)
      return false;
    return this.locks.has(file.path);
  }
  getAllActiveLocks() {
    return Array.from(this.locks.values());
  }
  async unlockFile(file) {
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.agent_state = "idle";
        delete fm.locked_by;
        delete fm.locked_at;
      });
      this.locks.delete(file.path);
      this.notifyListeners();
      new import_obsidian3.Notice(`\u{1F513} Notiz "${file.basename}" wurde freigegeben.`);
      return true;
    } catch (err) {
      console.error("Fehler beim Freigeben der Datei:", err);
      new import_obsidian3.Notice(`\u274C Fehler beim Freigeben von "${file.basename}".`);
      return false;
    }
  }
  async unlockAll() {
    const activeLocks = this.getAllActiveLocks();
    if (activeLocks.length === 0) {
      new import_obsidian3.Notice("Keine gesperrten Dateien vorhanden.");
      return 0;
    }
    let unlockedCount = 0;
    for (const lock of activeLocks) {
      try {
        await this.app.fileManager.processFrontMatter(lock.file, (fm) => {
          fm.agent_state = "idle";
          delete fm.locked_by;
          delete fm.locked_at;
        });
        this.locks.delete(lock.path);
        unlockedCount++;
      } catch (err) {
        console.error(`Fehler beim Entsperren von ${lock.path}:`, err);
      }
    }
    this.notifyListeners();
    new import_obsidian3.Notice(`\u{1F513} ${unlockedCount} Datei(en) erfolgreich freigegeben.`);
    return unlockedCount;
  }
  subscribe(listener) {
    this.listeners.add(listener);
    listener(this.getAllActiveLocks());
    return () => this.listeners.delete(listener);
  }
  notifyListeners() {
    const active = this.getAllActiveLocks();
    for (const listener of this.listeners) {
      listener(active);
    }
  }
};

// src/lockModal.ts
var import_obsidian4 = require("obsidian");
var AgentLockOverviewModal = class extends import_obsidian4.Modal {
  lockManager;
  timerInterval = null;
  constructor(app, lockManager) {
    super(app);
    this.lockManager = lockManager;
  }
  onOpen() {
    this.render();
    this.startLiveTimer();
  }
  onClose() {
    this.stopLiveTimer();
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("agent-lock-modal");
    const locks = this.lockManager.getAllActiveLocks();
    const headerEl = contentEl.createDiv({ cls: "agent-lock-modal-header" });
    const titleEl = headerEl.createEl("h2", { text: "\u{1F916} Aktive Agenten-Sperren" });
    const countBadge = headerEl.createSpan({
      cls: "agent-lock-modal-count-badge",
      text: `${locks.length}`
    });
    if (locks.length === 0) {
      const emptyEl = contentEl.createDiv({ cls: "agent-lock-modal-empty" });
      const emptyIcon = emptyEl.createDiv({ cls: "agent-lock-modal-empty-icon" });
      (0, import_obsidian4.setIcon)(emptyIcon, "shield-check");
      emptyEl.createEl("p", {
        cls: "agent-lock-modal-empty-text",
        text: "Keine Notizen durch Agenten gesperrt. Alles frei bearbeitbar!"
      });
      const closeBtn = contentEl.createEl("button", {
        cls: "mod-cta agent-lock-modal-close-btn",
        text: "Schlie\xDFen"
      });
      closeBtn.addEventListener("click", () => this.close());
      return;
    }
    const listContainer = contentEl.createDiv({ cls: "agent-lock-modal-list" });
    for (const lock of locks) {
      const itemEl = listContainer.createDiv({ cls: "agent-lock-modal-item" });
      const infoEl = itemEl.createDiv({ cls: "agent-lock-modal-item-info" });
      const fileRow = infoEl.createDiv({ cls: "agent-lock-modal-item-title-row" });
      const fileIcon = fileRow.createSpan({ cls: "agent-lock-file-icon" });
      (0, import_obsidian4.setIcon)(fileIcon, "file-text");
      const fileLink = fileRow.createEl("a", {
        cls: "agent-lock-modal-file-link",
        text: lock.title
      });
      fileLink.addEventListener("click", (e) => {
        e.preventDefault();
        this.app.workspace.openLinkText(lock.path, "", false);
        this.close();
      });
      const metaRow = infoEl.createDiv({ cls: "agent-lock-modal-item-meta" });
      const agentBadge = metaRow.createSpan({
        cls: "agent-lock-modal-agent-badge",
        text: `\u{1F916} ${lock.lockedBy}`
      });
      const timerSpan = metaRow.createSpan({
        cls: "agent-lock-modal-timer-span",
        text: `\u23F1\uFE0F ${this.getDurationText(lock.lockedAtDate)}`
      });
      timerSpan.setAttribute("data-path", lock.path);
      const actionsEl = itemEl.createDiv({ cls: "agent-lock-modal-item-actions" });
      const openBtn = actionsEl.createEl("button", {
        cls: "agent-lock-btn-secondary",
        text: "\xD6ffnen"
      });
      openBtn.addEventListener("click", () => {
        this.app.workspace.openLinkText(lock.path, "", false);
        this.close();
      });
      const unlockBtn = actionsEl.createEl("button", {
        cls: "agent-lock-btn-unlock-small",
        text: "\u{1F513} Freigeben"
      });
      unlockBtn.addEventListener("click", async () => {
        unlockBtn.disabled = true;
        unlockBtn.setText("...");
        await this.lockManager.unlockFile(lock.file);
        this.render();
      });
    }
    const footerEl = contentEl.createDiv({ cls: "agent-lock-modal-footer" });
    const unlockAllBtn = footerEl.createEl("button", {
      cls: "agent-lock-btn-danger",
      text: "\u{1F513} Alle freigeben (Emergency Unlock)"
    });
    unlockAllBtn.addEventListener("click", async () => {
      unlockAllBtn.disabled = true;
      unlockAllBtn.setText("Alle werden freigegeben...");
      await this.lockManager.unlockAll();
      this.close();
    });
  }
  startLiveTimer() {
    this.stopLiveTimer();
    this.timerInterval = window.setInterval(() => {
      const timerSpans = this.contentEl.querySelectorAll(".agent-lock-modal-timer-span");
      timerSpans.forEach((span) => {
        const path = span.getAttribute("data-path");
        if (path) {
          const file = this.app.vault.getAbstractFileByPath(path);
          if (file instanceof import_obsidian4.TFile) {
            const lock = this.lockManager.getLockInfo(file);
            if (lock) {
              span.setText(`\u23F1\uFE0F ${this.getDurationText(lock.lockedAtDate)}`);
            }
          }
        }
      });
    }, 1e3);
  }
  stopLiveTimer() {
    if (this.timerInterval !== null) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  getDurationText(lockedAtDate) {
    if (!lockedAtDate)
      return "aktiv";
    const now = /* @__PURE__ */ new Date();
    const diffSec = Math.max(0, Math.floor((now.getTime() - lockedAtDate.getTime()) / 1e3));
    if (diffSec < 60)
      return `vor ${diffSec}s`;
    const mins = Math.floor(diffSec / 60);
    const remainingSec = diffSec % 60;
    return `vor ${mins}m ${remainingSec}s`;
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");
var AgentLockSettingTab = class extends import_obsidian5.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F6E1}\uFE0F Agent Lock Guard Einstellungen" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Multi-Agent Concurrency Control, Live In-Note Locking Banners und Kollisionsschutz f\xFCr Obsidian WorkOS."
    });
    containerEl.createEl("h3", { text: "\u{1F512} Sperr- & Sicherheitsverhalten" });
    new import_obsidian5.Setting(containerEl).setName("Automatischer Lesemodus bei Sperre").setDesc("Schaltet gesperrte Notizen beim \xD6ffnen automatisch in den Lesemodus (Preview), sodass die Bearbeitung physisch gesperrt ist.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.forceReadingModeOnLock).onChange(async (value) => {
        this.plugin.settings.forceReadingModeOnLock = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("CodeMirror Engine Hard-Block").setDesc("Blockiert Text\xE4nderungen auf CodeMirror-Engine-Ebene (Transaktions-Filter), selbst wenn sich die Notiz im Quelltext-Modus befindet.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableHardBlock).onChange(async (value) => {
        this.plugin.settings.enableHardBlock = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Automatischer Timeout (Deadlock-Schutz)").setDesc("Gibt gesperrte Dateien automatisch frei, wenn seit dem Sperr-Zeitpunkt keine Aktivit\xE4t mehr stattgefunden hat (z. B. nach Agenten-Absturz).").addDropdown(
      (dropdown) => dropdown.addOption("0", "Aus (Streng manuell - Empfohlen)").addOption("1", "Nach 1 Minute").addOption("2", "Nach 2 Minuten").addOption("3", "Nach 3 Minuten").addOption("5", "Nach 5 Minuten").addOption("10", "Nach 10 Minuten").setValue(String(this.plugin.settings.autoUnlockTimeoutMinutes)).onChange(async (value) => {
        this.plugin.settings.autoUnlockTimeoutMinutes = parseInt(value, 10);
        await this.plugin.saveSettings();
        this.plugin.lockManager.updateSettings(this.plugin.settings);
      })
    );
    containerEl.createEl("h3", { text: "\u{1F3F7}\uFE0F Visueller Notiz-Banner (Header-UI)" });
    new import_obsidian5.Setting(containerEl).setName("Schwebenden Header-Banner anzeigen").setDesc("Blendet den eleganten Status-Banner oben in jeder durch einen Agenten gesperrten Notiz ein.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showBanner).onChange(async (value) => {
        this.plugin.settings.showBanner = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Live-Timer im Banner").setDesc("Zeigt sekundengenau an, wie lange die Notiz durch den Agenten bereits in Bearbeitung ist.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showTimer).onChange(async (value) => {
        this.plugin.settings.showTimer = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Sticky Banner beim Scrollen").setDesc("H\xE4lt den Banner beim Scrollen durch lange Notizen dezent am oberen Bildschirmrand fixiert.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stickyBanner).onChange(async (value) => {
        this.plugin.settings.stickyBanner = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Banner-Designstil").setDesc("W\xE4hle das visuelle Erscheinungsbild des In-Note Banners.").addDropdown(
      (dropdown) => dropdown.addOption("glassmorphism", "Modern Glassmorphism (Gradient + Blur)").addOption("solid", "Kompakter Solid Card").addOption("minimal", "Minimalistischer Text-Header").setValue(this.plugin.settings.bannerStyle).onChange(async (value) => {
        this.plugin.settings.bannerStyle = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F4CA} Statusleiste & Navigation" });
    new import_obsidian5.Setting(containerEl).setName("Statusleisten-Element").setDesc("Zeigt ein Icon mit der Anzahl aktiver Agenten-Locks in der unteren Obsidian-Statusleiste an.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableStatusBar).onChange(async (value) => {
        this.plugin.settings.enableStatusBar = value;
        await this.plugin.saveSettings();
        this.plugin.updateStatusBar();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Statusleiste bei 0 Locks ausblenden").setDesc("Versteckt das Statusleisten-Icon komplett, solange keine Dateien gesperrt sind.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hideStatusBarWhenZero).onChange(async (value) => {
        this.plugin.settings.hideStatusBarWhenZero = value;
        await this.plugin.saveSettings();
        this.plugin.updateStatusBar();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Ribbon-Icon (Linke Leiste)").setDesc("Zeigt ein Roboter-Icon in der linken Men\xFCleiste an, um das Lock-Modal mit 1 Klick zu \xF6ffnen.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableRibbonIcon).onChange(async (value) => {
        this.plugin.settings.enableRibbonIcon = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F514} Benachrichtigungen & Feedback" });
    new import_obsidian5.Setting(containerEl).setName("Abschluss-Benachrichtigungen").setDesc("Zeigt einen Hinweis an ('\u2705 [Agent] hat [Notiz] fertiggestellt'), sobald eine Sperre aufgehoben wird.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCompletionToasts).onChange(async (value) => {
        this.plugin.settings.enableCompletionToasts = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Tippversuch-Hinweise").setDesc("Zeigt eine Toast-Meldung an, wenn versucht wird, in eine gesperrte Notiz zu tippen.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableBlockedEditToasts).onChange(async (value) => {
        this.plugin.settings.enableBlockedEditToasts = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F6A8} Notfall-Werkzeuge (Emergency Utilities)" });
    const activeLocks = this.plugin.lockManager.getAllActiveLocks();
    const emergencySetting = new import_obsidian5.Setting(containerEl).setName("Alle Sperren im Vault aufheben").setDesc(`Aktuell gesperrte Dateien im Vault: ${activeLocks.length}`).addButton(
      (btn) => btn.setButtonText("\u{1F513} Alle sofort freigeben").setWarning().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Wird freigegeben...");
        const count = await this.plugin.lockManager.unlockAll();
        this.display();
      })
    );
  }
};

// src/statusBar.ts
var StatusBarManager = class {
  app;
  lockManager;
  statusBarEl = null;
  unsubscribe = null;
  settings = DEFAULT_SETTINGS;
  constructor(app, lockManager, settings) {
    this.app = app;
    this.lockManager = lockManager;
    if (settings)
      this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
    const active = this.lockManager.getAllActiveLocks();
    this.update(active.length);
  }
  init(statusBarEl) {
    this.statusBarEl = statusBarEl;
    this.statusBarEl.addClass("agent-lock-status-bar");
    this.statusBarEl.setAttribute("aria-label", "Agent Lock Guard: Klicken f\xFCr \xDCbersicht");
    this.statusBarEl.addEventListener("click", () => {
      new AgentLockOverviewModal(this.app, this.lockManager).open();
    });
    this.unsubscribe = this.lockManager.subscribe((locks) => {
      this.update(locks.length);
    });
  }
  destroy() {
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = null;
    }
  }
  update(count) {
    if (!this.statusBarEl)
      return;
    this.statusBarEl.empty();
    if (!this.settings.enableStatusBar) {
      this.statusBarEl.style.display = "none";
      return;
    }
    if (this.settings.hideStatusBarWhenZero && count === 0) {
      this.statusBarEl.style.display = "none";
      return;
    }
    this.statusBarEl.style.display = "inline-flex";
    const iconSpan = this.statusBarEl.createSpan({ cls: "agent-lock-status-icon" });
    iconSpan.setText("\u{1F916}");
    const textSpan = this.statusBarEl.createSpan({ cls: "agent-lock-status-text" });
    if (count === 0) {
      this.statusBarEl.removeClass("has-active-locks");
      textSpan.setText("0 Locks");
    } else {
      this.statusBarEl.addClass("has-active-locks");
      textSpan.setText(`${count} Lock${count > 1 ? "s" : ""} aktiv`);
    }
  }
};

// src/main.ts
var AgentLockGuardPlugin = class extends import_obsidian6.Plugin {
  settings = DEFAULT_SETTINGS;
  lockManager;
  bannerViewManager;
  statusBarManager;
  ribbonIconEl = null;
  async onload() {
    console.log("Loading Agent Lock Guard plugin...");
    await this.loadSettings();
    this.lockManager = new LockManager(this.app, (file, lockedBy) => {
      if (this.settings.enableCompletionToasts) {
        new import_obsidian6.Notice(`\u2705 ${lockedBy} hat Bearbeitung von "${file.basename}" beendet.`);
      }
      this.refreshBanner();
    });
    this.bannerViewManager = new BannerViewManager(this.lockManager, this.settings);
    this.bannerViewManager.init();
    setEditorLockManager(this.app, this.lockManager, this.settings);
    this.registerEditorExtension(createEditorLockExtension());
    if (this.settings.enableRibbonIcon) {
      this.ribbonIconEl = this.addRibbonIcon("bot", "Agent Lock Guard: Gesperrte Dateien", () => {
        new AgentLockOverviewModal(this.app, this.lockManager).open();
      });
    }
    if (this.settings.enableStatusBar) {
      const statusBarItem = this.addStatusBarItem();
      this.statusBarManager = new StatusBarManager(this.app, this.lockManager, this.settings);
      this.statusBarManager.init(statusBarItem);
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.refreshBanner();
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
        this.refreshBanner();
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.refreshBanner();
      })
    );
    this.lockManager.subscribe(() => {
      this.refreshBanner();
    });
    this.addCommand({
      id: "open-agent-lock-overview",
      name: "Gesperrte Dateien verwalten (Modal \xF6ffnen)",
      callback: () => {
        new AgentLockOverviewModal(this.app, this.lockManager).open();
      }
    });
    this.addCommand({
      id: "unlock-active-note",
      name: "Aktuelle Notiz freigeben",
      checkCallback: (checking) => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
        if (activeView && activeView.file) {
          const isLocked = this.lockManager.isFileLocked(activeView.file);
          if (isLocked) {
            if (!checking) {
              this.lockManager.unlockFile(activeView.file);
            }
            return true;
          }
        }
        return false;
      }
    });
    this.addCommand({
      id: "unlock-all-notes",
      name: "Alle gesperrten Dateien freigeben (Emergency Unlock All)",
      callback: async () => {
        await this.lockManager.unlockAll();
      }
    });
    this.addSettingTab(new AgentLockSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.lockManager.init(this.settings);
      this.refreshBanner();
    });
  }
  onunload() {
    console.log("Unloading Agent Lock Guard plugin...");
    this.bannerViewManager.destroy();
    this.lockManager.destroy();
    if (this.statusBarManager) {
      this.statusBarManager.destroy();
    }
  }
  refreshBanner() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!activeView)
      return;
    const file = activeView.file;
    const isLocked = file ? this.lockManager.isFileLocked(file) : false;
    if (isLocked) {
      activeView.containerEl.addClass("is-agent-locked");
      if (this.settings.forceReadingModeOnLock && activeView.getMode() !== "preview") {
        activeView.setState({ ...activeView.getState(), mode: "preview" }, { history: false });
      }
    } else {
      activeView.containerEl.removeClass("is-agent-locked");
    }
    this.bannerViewManager.updateBannerForView(activeView);
  }
  updateStatusBar() {
    if (this.statusBarManager) {
      this.statusBarManager.updateSettings(this.settings);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.lockManager.updateSettings(this.settings);
    this.bannerViewManager.updateSettings(this.settings);
    updateEditorLockSettings(this.settings);
    this.updateStatusBar();
  }
};
