/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Agent Lock Guard - Multi-Agent Concurrency & Collision Guard for Obsidian
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AgentLockGuardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/bannerView.ts
var import_obsidian = require("obsidian");
var BannerViewManager = class {
  constructor(lockManager) {
    this.timerInterval = null;
    this.currentBannerEl = null;
    this.currentLockedFile = null;
    this.lockManager = lockManager;
  }
  init() {
    this.startTimerLoop();
  }
  destroy() {
    this.stopTimerLoop();
    this.removeBanner();
  }
  updateBannerForView(view) {
    if (!view || !view.file) {
      this.removeBanner();
      return;
    }
    const file = view.file;
    const lockInfo = this.lockManager.getLockInfo(file);
    if (lockInfo && lockInfo.agentState === "processing") {
      this.renderBanner(view, lockInfo);
    } else {
      this.removeBanner();
    }
  }
  renderBanner(view, lockInfo) {
    this.currentLockedFile = lockInfo.file;
    const container = view.contentEl;
    let bannerEl = container.querySelector(".agent-lock-banner");
    if (!bannerEl) {
      bannerEl = createDiv({ cls: "agent-lock-banner" });
      container.prepend(bannerEl);
      this.currentBannerEl = bannerEl;
    }
    bannerEl.empty();
    const leftEl = bannerEl.createDiv({ cls: "agent-lock-banner-left" });
    const pulseEl = leftEl.createDiv({ cls: "agent-lock-pulse" });
    const iconEl = leftEl.createSpan({ cls: "agent-lock-icon" });
    (0, import_obsidian.setIcon)(iconEl, "bot");
    const textEl = leftEl.createDiv({ cls: "agent-lock-text-container" });
    const titleEl = textEl.createDiv({ cls: "agent-lock-title" });
    titleEl.createSpan({ text: "AGENT ARBEITET " });
    titleEl.createSpan({ cls: "agent-lock-agent-name", text: `(${lockInfo.lockedBy})` });
    const descEl = textEl.createDiv({ cls: "agent-lock-desc" });
    descEl.setText("Schreibgesch\xFCtzt, um Kollisionen zu verhindern.");
    const rightEl = bannerEl.createDiv({ cls: "agent-lock-banner-right" });
    const timerBadge = rightEl.createDiv({ cls: "agent-lock-timer-badge" });
    const timerIcon = timerBadge.createSpan({ cls: "agent-lock-timer-icon" });
    (0, import_obsidian.setIcon)(timerIcon, "clock");
    const timerText = timerBadge.createSpan({ cls: "agent-lock-timer-text" });
    timerText.setText(this.calculateDurationText(lockInfo.lockedAtDate));
    const unlockBtn = rightEl.createEl("button", {
      cls: "agent-lock-unlock-btn",
      text: "\u{1F513} Jetzt freigeben"
    });
    unlockBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      unlockBtn.disabled = true;
      unlockBtn.setText("Wird freigegeben...");
      await this.lockManager.unlockFile(lockInfo.file);
    });
  }
  removeBanner() {
    if (this.currentBannerEl) {
      this.currentBannerEl.remove();
      this.currentBannerEl = null;
    }
    this.currentLockedFile = null;
  }
  startTimerLoop() {
    this.stopTimerLoop();
    this.timerInterval = window.setInterval(() => {
      if (!this.currentBannerEl || !this.currentLockedFile)
        return;
      const lock = this.lockManager.getLockInfo(this.currentLockedFile);
      if (!lock)
        return;
      const timerTextEl = this.currentBannerEl.querySelector(".agent-lock-timer-text");
      if (timerTextEl) {
        timerTextEl.setText(this.calculateDurationText(lock.lockedAtDate));
      }
    }, 1e3);
  }
  stopTimerLoop() {
    if (this.timerInterval !== null) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  calculateDurationText(lockedAtDate) {
    if (!lockedAtDate)
      return "aktiv";
    const now = /* @__PURE__ */ new Date();
    const diffSec = Math.max(0, Math.floor((now.getTime() - lockedAtDate.getTime()) / 1e3));
    if (diffSec < 60) {
      return `seit ${diffSec}s`;
    }
    const mins = Math.floor(diffSec / 60);
    const remainingSec = diffSec % 60;
    return `seit ${mins}m ${remainingSec}s`;
  }
};

// src/editorExtension.ts
var import_view = require("@codemirror/view");
var import_obsidian2 = require("obsidian");
var activeLockManager = null;
var lastNoticeTime = 0;
function setEditorLockManager(manager) {
  activeLockManager = manager;
}
function createEditorLockExtension() {
  return import_view.EditorView.domEventHandlers({
    keydown(event, view) {
      if (!activeLockManager)
        return false;
      if (event.key === "ArrowUp" || event.key === "ArrowDown" || event.key === "ArrowLeft" || event.key === "ArrowRight" || event.key === "PageUp" || event.key === "PageDown" || event.key === "Home" || event.key === "End" || event.key === "Escape" || event.key === "Control" || event.key === "Alt" || event.key === "Shift" || event.key === "Meta") {
        return false;
      }
      const file = view.editor?.file || null;
      const isLocked = activeLockManager.getAllActiveLocks().some(
        (lock) => lock.agentState === "processing"
      );
      const dom = view.dom.closest(".workspace-leaf");
      const hasLockBanner = dom?.querySelector(".agent-lock-banner") !== null;
      if (hasLockBanner) {
        event.preventDefault();
        event.stopPropagation();
        const now = Date.now();
        if (now - lastNoticeTime > 2500) {
          lastNoticeTime = now;
          new import_obsidian2.Notice("\u{1F512} Notiz ist durch Agent gesperrt. Klicke oben auf 'Freigeben' zum Bearbeiten.", 3e3);
        }
        return true;
      }
      return false;
    },
    paste(event, view) {
      const dom = view.dom.closest(".workspace-leaf");
      const hasLockBanner = dom?.querySelector(".agent-lock-banner") !== null;
      if (hasLockBanner) {
        event.preventDefault();
        event.stopPropagation();
        new import_obsidian2.Notice("\u{1F512} Notiz ist durch Agent gesperrt. Einf\xFCgen blockiert.", 3e3);
        return true;
      }
      return false;
    },
    cut(event, view) {
      const dom = view.dom.closest(".workspace-leaf");
      const hasLockBanner = dom?.querySelector(".agent-lock-banner") !== null;
      if (hasLockBanner) {
        event.preventDefault();
        event.stopPropagation();
        new import_obsidian2.Notice("\u{1F512} Notiz ist durch Agent gesperrt. Ausschneiden blockiert.", 3e3);
        return true;
      }
      return false;
    }
  });
}

// src/lockManager.ts
var import_obsidian3 = require("obsidian");
var LockManager = class {
  constructor(app, onFileCompleted) {
    this.locks = /* @__PURE__ */ new Map();
    this.listeners = /* @__PURE__ */ new Set();
    this.eventRefs = [];
    this.app = app;
    this.onFileCompletedCallback = onFileCompleted;
  }
  init() {
    this.scanVault();
    const cacheRef = this.app.metadataCache.on("changed", (file) => {
      if (file instanceof import_obsidian3.TFile && file.extension === "md") {
        this.evaluateFile(file);
      }
    });
    this.eventRefs.push(cacheRef);
    const renameRef = this.app.vault.on("rename", (file, oldPath) => {
      if (this.locks.has(oldPath)) {
        const oldLock = this.locks.get(oldPath);
        this.locks.delete(oldPath);
        if (file instanceof import_obsidian3.TFile) {
          oldLock.file = file;
          oldLock.path = file.path;
          this.locks.set(file.path, oldLock);
          this.notifyListeners();
        }
      }
    });
    this.eventRefs.push(renameRef);
    const deleteRef = this.app.vault.on("delete", (file) => {
      if (this.locks.has(file.path)) {
        this.locks.delete(file.path);
        this.notifyListeners();
      }
    });
    this.eventRefs.push(deleteRef);
  }
  destroy() {
    for (const ref of this.eventRefs) {
      this.app.metadataCache.offref(ref);
      this.app.vault.offref(ref);
    }
    this.eventRefs = [];
    this.locks.clear();
    this.listeners.clear();
  }
  scanVault() {
    const files = this.app.vault.getMarkdownFiles();
    this.locks.clear();
    for (const file of files) {
      const lockInfo = this.extractLockInfo(file);
      if (lockInfo && lockInfo.agentState === "processing") {
        this.locks.set(file.path, lockInfo);
      }
    }
    this.notifyListeners();
  }
  evaluateFile(file) {
    const previousLock = this.locks.get(file.path);
    const currentLock = this.extractLockInfo(file);
    if (currentLock && currentLock.agentState === "processing") {
      this.locks.set(file.path, currentLock);
      this.notifyListeners();
    } else {
      if (previousLock) {
        this.locks.delete(file.path);
        this.notifyListeners();
        if (this.onFileCompletedCallback) {
          this.onFileCompletedCallback(file, previousLock.lockedBy);
        }
      }
    }
  }
  extractLockInfo(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache || !cache.frontmatter)
      return null;
    const fm = cache.frontmatter;
    const agentState = fm.agent_state;
    const lockedBy = fm.locked_by || "KI-Agent";
    const lockedAt = fm.locked_at || null;
    if (agentState === "processing") {
      let lockedAtDate = null;
      if (lockedAt) {
        const parsed = new Date(lockedAt);
        if (!isNaN(parsed.getTime())) {
          lockedAtDate = parsed;
        }
      }
      return {
        file,
        path: file.path,
        title: fm.title || file.basename,
        agentState: "processing",
        lockedBy,
        lockedAt,
        lockedAtDate
      };
    }
    return null;
  }
  getLockInfo(file) {
    if (!file)
      return null;
    return this.locks.get(file.path) || null;
  }
  isFileLocked(file) {
    if (!file)
      return false;
    return this.locks.has(file.path);
  }
  getAllActiveLocks() {
    return Array.from(this.locks.values());
  }
  async unlockFile(file) {
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.agent_state = "idle";
        delete fm.locked_by;
        delete fm.locked_at;
      });
      this.locks.delete(file.path);
      this.notifyListeners();
      new import_obsidian3.Notice(`\u{1F513} Notiz "${file.basename}" wurde freigegeben.`);
      return true;
    } catch (err) {
      console.error("Fehler beim Freigeben der Datei:", err);
      new import_obsidian3.Notice(`\u274C Fehler beim Freigeben von "${file.basename}".`);
      return false;
    }
  }
  async unlockAll() {
    const activeLocks = this.getAllActiveLocks();
    if (activeLocks.length === 0) {
      new import_obsidian3.Notice("Keine gesperrten Dateien vorhanden.");
      return 0;
    }
    let unlockedCount = 0;
    for (const lock of activeLocks) {
      try {
        await this.app.fileManager.processFrontMatter(lock.file, (fm) => {
          fm.agent_state = "idle";
          delete fm.locked_by;
          delete fm.locked_at;
        });
        this.locks.delete(lock.path);
        unlockedCount++;
      } catch (err) {
        console.error(`Fehler beim Entsperren von ${lock.path}:`, err);
      }
    }
    this.notifyListeners();
    new import_obsidian3.Notice(`\u{1F513} ${unlockedCount} Datei(en) erfolgreich freigegeben.`);
    return unlockedCount;
  }
  subscribe(listener) {
    this.listeners.add(listener);
    listener(this.getAllActiveLocks());
    return () => this.listeners.delete(listener);
  }
  notifyListeners() {
    const active = this.getAllActiveLocks();
    for (const listener of this.listeners) {
      listener(active);
    }
  }
};

// src/lockModal.ts
var import_obsidian4 = require("obsidian");
var AgentLockOverviewModal = class extends import_obsidian4.Modal {
  constructor(app, lockManager) {
    super(app);
    this.timerInterval = null;
    this.lockManager = lockManager;
  }
  onOpen() {
    this.render();
    this.startLiveTimer();
  }
  onClose() {
    this.stopLiveTimer();
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("agent-lock-modal");
    const locks = this.lockManager.getAllActiveLocks();
    const headerEl = contentEl.createDiv({ cls: "agent-lock-modal-header" });
    const titleEl = headerEl.createEl("h2", { text: "\u{1F916} Aktive Agenten-Sperren" });
    const countBadge = headerEl.createSpan({
      cls: "agent-lock-modal-count-badge",
      text: `${locks.length}`
    });
    if (locks.length === 0) {
      const emptyEl = contentEl.createDiv({ cls: "agent-lock-modal-empty" });
      const emptyIcon = emptyEl.createDiv({ cls: "agent-lock-modal-empty-icon" });
      (0, import_obsidian4.setIcon)(emptyIcon, "shield-check");
      emptyEl.createEl("p", {
        cls: "agent-lock-modal-empty-text",
        text: "Keine Notizen durch Agenten gesperrt. Alles frei bearbeitbar!"
      });
      const closeBtn = contentEl.createEl("button", {
        cls: "mod-cta agent-lock-modal-close-btn",
        text: "Schlie\xDFen"
      });
      closeBtn.addEventListener("click", () => this.close());
      return;
    }
    const listContainer = contentEl.createDiv({ cls: "agent-lock-modal-list" });
    for (const lock of locks) {
      const itemEl = listContainer.createDiv({ cls: "agent-lock-modal-item" });
      const infoEl = itemEl.createDiv({ cls: "agent-lock-modal-item-info" });
      const fileRow = infoEl.createDiv({ cls: "agent-lock-modal-item-title-row" });
      const fileIcon = fileRow.createSpan({ cls: "agent-lock-file-icon" });
      (0, import_obsidian4.setIcon)(fileIcon, "file-text");
      const fileLink = fileRow.createEl("a", {
        cls: "agent-lock-modal-file-link",
        text: lock.title
      });
      fileLink.addEventListener("click", (e) => {
        e.preventDefault();
        this.app.workspace.openLinkText(lock.path, "", false);
        this.close();
      });
      const metaRow = infoEl.createDiv({ cls: "agent-lock-modal-item-meta" });
      const agentBadge = metaRow.createSpan({
        cls: "agent-lock-modal-agent-badge",
        text: `\u{1F916} ${lock.lockedBy}`
      });
      const timerSpan = metaRow.createSpan({
        cls: "agent-lock-modal-timer-span",
        text: `\u23F1\uFE0F ${this.getDurationText(lock.lockedAtDate)}`
      });
      timerSpan.setAttribute("data-path", lock.path);
      const actionsEl = itemEl.createDiv({ cls: "agent-lock-modal-item-actions" });
      const openBtn = actionsEl.createEl("button", {
        cls: "agent-lock-btn-secondary",
        text: "\xD6ffnen"
      });
      openBtn.addEventListener("click", () => {
        this.app.workspace.openLinkText(lock.path, "", false);
        this.close();
      });
      const unlockBtn = actionsEl.createEl("button", {
        cls: "agent-lock-btn-unlock-small",
        text: "\u{1F513} Freigeben"
      });
      unlockBtn.addEventListener("click", async () => {
        unlockBtn.disabled = true;
        unlockBtn.setText("...");
        await this.lockManager.unlockFile(lock.file);
        this.render();
      });
    }
    const footerEl = contentEl.createDiv({ cls: "agent-lock-modal-footer" });
    const unlockAllBtn = footerEl.createEl("button", {
      cls: "agent-lock-btn-danger",
      text: "\u{1F513} Alle freigeben (Emergency Unlock)"
    });
    unlockAllBtn.addEventListener("click", async () => {
      unlockAllBtn.disabled = true;
      unlockAllBtn.setText("Alle werden freigegeben...");
      await this.lockManager.unlockAll();
      this.close();
    });
  }
  startLiveTimer() {
    this.stopLiveTimer();
    this.timerInterval = window.setInterval(() => {
      const timerSpans = this.contentEl.querySelectorAll(".agent-lock-modal-timer-span");
      timerSpans.forEach((span) => {
        const path = span.getAttribute("data-path");
        if (path) {
          const file = this.app.vault.getAbstractFileByPath(path);
          if (file instanceof import_obsidian4.TFile) {
            const lock = this.lockManager.getLockInfo(file);
            if (lock) {
              span.setText(`\u23F1\uFE0F ${this.getDurationText(lock.lockedAtDate)}`);
            }
          }
        }
      });
    }, 1e3);
  }
  stopLiveTimer() {
    if (this.timerInterval !== null) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  getDurationText(lockedAtDate) {
    if (!lockedAtDate)
      return "aktiv";
    const now = /* @__PURE__ */ new Date();
    const diffSec = Math.max(0, Math.floor((now.getTime() - lockedAtDate.getTime()) / 1e3));
    if (diffSec < 60)
      return `vor ${diffSec}s`;
    const mins = Math.floor(diffSec / 60);
    const remainingSec = diffSec % 60;
    return `vor ${mins}m ${remainingSec}s`;
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");
var AgentLockSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Agent Lock Guard Einstellungen" });
    new import_obsidian5.Setting(containerEl).setName("Statusleiste anzeigen").setDesc("Zeigt ein Icon mit der Anzahl aktiver Agenten-Locks in der unteren Statusleiste an.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableStatusBar).onChange(async (value) => {
        this.plugin.settings.enableStatusBar = value;
        await this.plugin.saveSettings();
        this.plugin.updateStatusBar();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Ribbon-Icon anzeigen").setDesc("F\xFCgt ein Icon zur linken Seitenleiste hinzu, um gesperrte Dateien mit einem Klick anzuzeigen.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableRibbonIcon).onChange(async (value) => {
        this.plugin.settings.enableRibbonIcon = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Abschluss-Benachrichtigungen").setDesc("Zeigt einen kurzen Hinweis an, wenn ein Agent die Bearbeitung einer Notiz beendet hat.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCompletionToasts).onChange(async (value) => {
        this.plugin.settings.enableCompletionToasts = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Live-Timer im Banner").setDesc("Zeigt sekundengenau an, seit wann die Notiz durch den Agenten gesperrt ist.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showTimer).onChange(async (value) => {
        this.plugin.settings.showTimer = value;
        await this.plugin.saveSettings();
        this.plugin.refreshBanner();
      })
    );
  }
};

// src/statusBar.ts
var StatusBarManager = class {
  constructor(app, lockManager) {
    this.statusBarEl = null;
    this.unsubscribe = null;
    this.app = app;
    this.lockManager = lockManager;
  }
  init(statusBarEl) {
    this.statusBarEl = statusBarEl;
    this.statusBarEl.addClass("agent-lock-status-bar");
    this.statusBarEl.setAttribute("aria-label", "Agent Lock Guard: Klicken f\xFCr \xDCbersicht");
    this.statusBarEl.addEventListener("click", () => {
      new AgentLockOverviewModal(this.app, this.lockManager).open();
    });
    this.unsubscribe = this.lockManager.subscribe((locks) => {
      this.update(locks.length);
    });
  }
  destroy() {
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = null;
    }
  }
  update(count) {
    if (!this.statusBarEl)
      return;
    this.statusBarEl.empty();
    const iconSpan = this.statusBarEl.createSpan({ cls: "agent-lock-status-icon" });
    iconSpan.setText("\u{1F916}");
    const textSpan = this.statusBarEl.createSpan({ cls: "agent-lock-status-text" });
    if (count === 0) {
      this.statusBarEl.removeClass("has-active-locks");
      textSpan.setText("0 Locks");
    } else {
      this.statusBarEl.addClass("has-active-locks");
      textSpan.setText(`${count} Lock${count > 1 ? "s" : ""} aktiv`);
    }
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  enableStatusBar: true,
  enableRibbonIcon: true,
  enableCompletionToasts: true,
  showTimer: true
};

// src/main.ts
var AgentLockGuardPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.ribbonIconEl = null;
  }
  async onload() {
    console.log("Loading Agent Lock Guard plugin...");
    await this.loadSettings();
    this.lockManager = new LockManager(this.app, (file, lockedBy) => {
      if (this.settings.enableCompletionToasts) {
        new import_obsidian6.Notice(`\u2705 ${lockedBy} hat Bearbeitung von "${file.basename}" beendet.`);
      }
    });
    this.bannerViewManager = new BannerViewManager(this.lockManager);
    this.bannerViewManager.init();
    setEditorLockManager(this.lockManager);
    this.registerEditorExtension(createEditorLockExtension());
    if (this.settings.enableRibbonIcon) {
      this.ribbonIconEl = this.addRibbonIcon("bot", "Agent Lock Guard: Gesperrte Dateien", () => {
        new AgentLockOverviewModal(this.app, this.lockManager).open();
      });
    }
    if (this.settings.enableStatusBar) {
      const statusBarItem = this.addStatusBarItem();
      this.statusBarManager = new StatusBarManager(this.app, this.lockManager);
      this.statusBarManager.init(statusBarItem);
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.refreshBanner();
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
        this.refreshBanner();
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.refreshBanner();
      })
    );
    this.lockManager.subscribe(() => {
      this.refreshBanner();
    });
    this.addCommand({
      id: "open-agent-lock-overview",
      name: "Gesperrte Dateien verwalten (Modal \xF6ffnen)",
      callback: () => {
        new AgentLockOverviewModal(this.app, this.lockManager).open();
      }
    });
    this.addCommand({
      id: "unlock-active-note",
      name: "Aktuelle Notiz freigeben",
      checkCallback: (checking) => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
        if (activeView && activeView.file) {
          const isLocked = this.lockManager.isFileLocked(activeView.file);
          if (isLocked) {
            if (!checking) {
              this.lockManager.unlockFile(activeView.file);
            }
            return true;
          }
        }
        return false;
      }
    });
    this.addCommand({
      id: "unlock-all-notes",
      name: "Alle gesperrten Dateien freigeben (Emergency Unlock All)",
      callback: async () => {
        await this.lockManager.unlockAll();
      }
    });
    this.addSettingTab(new AgentLockSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.lockManager.init();
      this.refreshBanner();
    });
  }
  onunload() {
    console.log("Unloading Agent Lock Guard plugin...");
    this.bannerViewManager.destroy();
    this.lockManager.destroy();
    if (this.statusBarManager) {
      this.statusBarManager.destroy();
    }
  }
  refreshBanner() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    this.bannerViewManager.updateBannerForView(activeView);
  }
  updateStatusBar() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
